/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.service;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.Admin;
import com.ymai.struts.FormUtil;

/** 
 * MyEclipse Struts
 * Creation date: 08-04-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class InAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String name = FormUtil.escape(request.getParameter("name"));
		String pass = FormUtil.escape(request.getParameter("pass"));
		Admin admin = ServiceFacade.login(name, pass);
		if(admin!=null){
			request.getSession().setAttribute("c_admin", admin);
			return mapping.findForward("welcome");
		}
		return mapping.findForward("again");
	}
}