/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 05-21-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ActivateCodeSendAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		String action = request.getParameter("action");
		if(action == null){
			try {
				String code = UserFacade.sendAcitveCode(request, UserValidate.getUnactiveUser(request).getUserTele());
				response.getWriter().write("1");
			} catch (Exception e) {
				response.getWriter().write("-1");
				e.printStackTrace();
			}
			return null;
		}
		if(action.equals("noUser")){
			try {
				String code = UserFacade.sendAcitveCode(request, UserValidate.getTele(request));
				response.getWriter().write("1");
			} catch (Exception e) {
				response.getWriter().write("-1");
				e.printStackTrace();
			}
			return null;
		}
		return null;
		
	}
}