/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.User;

/** 
 * MyEclipse Struts
 * Creation date: 05-20-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ActivateAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		String action = request.getParameter("action");
		if(action == null){
			String aCode = request.getParameter("J_Code");
			String origin_aCode = UserFacade.getAcitveCode(request);
			Integer num = (Integer) session.getAttribute(UserFacade.KEY_ACTIVE_CODE_CHECK_NUM);
			
			if(aCode.equals(origin_aCode)){
				try {
					UserFacade.activeCurrentUser(request);
					return mapping.findForward("ok");
				} catch (Exception e) {
					session.setAttribute("ActivateAction_Mess", e.getMessage());
					return mapping.findForward("again");
				}
			}
			if(!aCode.equals(origin_aCode)){
				if(num==null)num = 0;
				num++;
				session.setAttribute(UserFacade.KEY_ACTIVE_CODE_CHECK_NUM, num);
				if(num >5){
					session.removeAttribute(UserFacade.KEY_ACTIVE_CODE);
					session.removeAttribute(UserFacade.KEY_ACTIVE_CODE_CHECK_NUM);
					session.setAttribute("ActivateAction_Mess", "尝试次数过多，验证码已更改并重新发送");
					try{
						UserFacade.sendAcitveCode(request, UserValidate.getUser(request).getUserTele());
					}catch(Exception e){
						session.setAttribute("ActivateAction_Mess", "尝试次数过多，验证码已更改并重新发送\n验证码发送失败,请重新发送");
					}
					return mapping.findForward("again");
				}
			}
		}
		if(action.equals("ac")){
			String origin_aCode = UserFacade.getAcitveCode(request);
			if(origin_aCode == null){
				try {
					UserFacade.sendAcitveCode(request, UserValidate.getUser(request).getUserTele());
					session.setAttribute("ActivateAction_Mess","验证码已发送到您的手机，请稍候" );
				} catch (Exception e) {
					session.setAttribute("ActivateAction_Mess","验证码发送失败，请重新发送" );
					e.printStackTrace();
				}
			}
			return mapping.findForward("again");
		}

		return null;
	}

}