/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user;

import java.io.IOException;
import java.io.Writer;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 06-17-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CheckAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		String type = request.getParameter("type");
		String value = request.getParameter("value");
		response.setCharacterEncoding("utf-8");
		Writer writer = response.getWriter();
		if(type == null || value == null) 
			return null;
		if(type.equals("phone")){
			if(UserFacade.canRegisterPhone(value)){
				writer.write("true");
				return null;
			}
			writer.write("false");
			return null;

		}
		if(type.equals("email")){
			if(UserFacade.canRegisterEmail(value)){
				writer.write("true");
				return null;
			}
			writer.write("false");
			return null;

		}
		return null;
	}
}