/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.User;

/** 
 * MyEclipse Struts
 * Creation date: 06-13-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User user = UserValidate.getUser(request);
		if(user == null ){
			return mapping.findForward("login");
		}
		if(user!=null){
			if(user.getUserState().equals(User.STATE_UN_ACTIVATE)){
				UserValidate.setUser(request, user);
				return mapping.findForward("activate");
			}
			if(!user.getUserState().equals(User.STATE_ACTIVE)){
				request.setAttribute("mess","登陆失败,请重新登陆.");
				return mapping.findForward("error");
			}
			UserValidate.setUser(request, user);
			if(user.getUserIsAdmin())
				return mapping.findForward("admin");
			if(user.getUserIsStore())
				return mapping.findForward("store");
			if(user.getUserIsUser())
				return mapping.findForward("user");
			
			return null;
			
		}
		return null;
	}
}