/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user;

import java.math.BigInteger;

import javax.servlet.ServletRequest;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

import com.ymai.struts.FormUtil;
import com.ymai.struts.IllegalParameter;

/** 
 * MyEclipse Struts
 * Creation date: 05-18-2010
 * 
 * XDoclet definition:
 * @struts.form name="registerForm"
 */
public class RegisterForm extends ValidatorForm  {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** vcode property */
	private String vcode;

	/** userEmail property */
	private String userEmail;

	/** userPassword property */
	private String userPassword;

	/** userTele property */
	private long userTele;
	
	/*
	 * Generated Methods
	 */
	public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request) {
		try {
			FormUtil.checkForm(this);
		} catch (IllegalParameter e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}


	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return FormUtil.escape(userName);
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the vcode.
	 * @return String
	 */
	public String getVcode() {
		return vcode;
	}

	/** 
	 * Set the vcode.
	 * @param vcode The vcode to set
	 */
	public void setVcode(String vcode) {
		this.vcode = vcode;
	}

	/** 
	 * Returns the userEmail.
	 * @return String
	 */
	public String getUserEmail() {
		return FormUtil.escape(userEmail);
	}

	/** 
	 * Set the userEmail.
	 * @param userEmail The userEmail to set
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/** 
	 * Returns the userPassword.
	 * @return String
	 */
	public String getUserPassword() {
		return FormUtil.escape(userPassword);
	}

	/** 
	 * Set the userPassword.
	 * @param userPassword The userPassword to set
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/** 
	 * Returns the userTele.
	 * @return long
	 */
	public long getUserTele() {
		return userTele;
	}

	/** 
	 * Set the userTele.
	 * @param userTele The userTele to set
	 */
	public void setUserTele(long userTele) {
		this.userTele = userTele;
	}
}