/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-02-2010
 * 
 * XDoclet definition:
 * @struts.form name="blockEditSubmitForm"
 */
public class BlockEditSubmitForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** distance property */
	private Double distance;

	/** store property */
	private Integer store;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the distance.
	 * @return Double
	 */
	public Double getDistance() {
		return distance;
	}

	/** 
	 * Set the distance.
	 * @param distance The distance to set
	 */
	public void setDistance(Double distance) {
		this.distance = distance;
	}

	/** 
	 * Returns the store.
	 * @return Integer
	 */
	public Integer getStore() {
		return store;
	}

	/** 
	 * Set the store.
	 * @param store The store to set
	 */
	public void setStore(Integer store) {
		this.store = store;
	}
}