/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.Order;
import com.ymai.struts.action.ordersystem.OSFacade;

/** 
 * MyEclipse Struts
 * Creation date: 07-05-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetOrderDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String action = request.getParameter("action");
		Integer orderId = Integer.valueOf(request.getParameter("order"));
		Order order = OSFacade.getOrderDetail(request, orderId);
		if(action == null){
			try {

				request.setAttribute("order", order);
				return mapping.findForward("detail");
			} catch (Exception e) {
				e.printStackTrace();
				return null;
			}
			
		}
		return null;
	}
}