/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.tools.Json;

/** 
 * MyEclipse Struts
 * Creation date: 06-16-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetValueAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		String type = request.getParameter("type");
		if(type == null)return null;
		if(type.equals("sendBlock")){
			StoreFacade.getStore(1);
		}
		if(type.equals("nearStore")){
			Integer storeId = Integer.valueOf(request.getParameter("store"));
			Float distance = Float.valueOf(request.getParameter("distance"));
			List block_list = StoreFacade.getBlockListNear(storeId, distance);
			String html = Json.toJson(block_list);
			response.setCharacterEncoding("utf-8");
			response.getWriter().write(html);
			return null;
		}
		return null;
	}
}