/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.jsp.PageContext;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;
import org.hibernate.Session;

import com.jspsmart.upload.SmartUpload;
import com.jspsmart.upload.SmartUploadException;
import com.ymai.hibernate.HibernateSessionFactory;
import com.ymai.hibernate.Item;
import com.ymai.hibernate.User;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 05-07-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ItemImageUpAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		
		ItemImageUpForm uForm = (ItemImageUpForm) form;
		Integer itemId = uForm.getItemId();
		FormFile file = uForm.getImage();
		
		User current = UserValidate.getUser(request);
		Session session = HibernateSessionFactory.getSessionFactory().getCurrentSession();
		UserValidate.canEditItem(request, itemId);
		Item item = (Item) session.load(Item.class, itemId);
		Integer storeId = item.getStore().getStoreId();
		response.setContentType("text/html;charset=utf-8"); 
		PrintWriter out = response.getWriter();
		String url  = null;
		try {
			url = FileUpHelper.saveItemImage(storeId, itemId, file, request);
			out.write("<script type='text/javascript'>parent.callback('上传成功','"+url+"');</script>");
			out.close();
		} catch (Exception e) {
			e.printStackTrace();
			out.write("<script type='text/javascript'>parent.callback('"+e.getMessage()+"')</script>");
			out.close();
		} 
		return null;
	}
}