/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-10-2010
 * 
 * XDoclet definition:
 * @struts.form name="itemEditForm"
 */
public class ItemEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** itemPrice property */
	private Double itemPrice;

	/** itemName property */
	private String itemName;

	/** itemId property */
	private Integer itemId;

	/** itemType property */
	private String itemType;


	/** itemState property */
	private String itemState;

	private Integer storeId;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the itemPrice.
	 * @return Double
	 */
	public Double getItemPrice() {
		return itemPrice;
	}

	/** 
	 * Set the itemPrice.
	 * @param itemPrice The itemPrice to set
	 */
	public void setItemPrice(Double itemPrice) {
		this.itemPrice = itemPrice;
	}



	/** 
	 * Returns the itemName.
	 * @return String
	 */
	public String getItemName() {
		return itemName;
	}

	/** 
	 * Set the itemName.
	 * @param itemName The itemName to set
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/** 
	 * Returns the itemId.
	 * @return Integer
	 */
	public Integer getItemId() {
		return itemId;
	}

	/** 
	 * Set the itemId.
	 * @param itemId The itemId to set
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/** 
	 * Returns the itemType.
	 * @return String
	 */
	public String getItemType() {
		return itemType;
	}

	/** 
	 * Set the itemType.
	 * @param itemType The itemType to set
	 */
	public void setItemType(String itemType) {
		this.itemType = itemType;
	}



	/** 
	 * Returns the itemState.
	 * @return String
	 */
	public String getItemState() {
		return itemState;
	}

	/** 
	 * Set the itemState.
	 * @param itemState The itemState to set
	 */
	public void setItemState(String itemState) {
		this.itemState = itemState;
	}
	
	/** 
	 * Returns the storeId.
	 * @return Integer
	 */
	public Integer getStoreId() {
		return storeId;
	}

	/** 
	 * Set the storeId.
	 * @param storeId The storeId to set
	 */
	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}
}