/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Hibernate;
import org.hibernate.Session;

import com.ymai.hibernate.HibernateSessionFactory;
import com.ymai.hibernate.Item;
import com.ymai.hibernate.Store;
import com.ymai.hibernate.User;
import com.ymai.struts.action.order.OrderFacade;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 05-07-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ItemEditAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User current = UserValidate.getUser(request);
		
		String itemStr = request.getParameter("item");
		if(itemStr!=null){
			Integer itemId = Integer.valueOf(itemStr);
			Item item = (Item) StoreFacade.getItem(itemId);
			List type_list = OrderFacade.getItemTypes(item.getStore().getStoreId());
			request.setAttribute("store", item.getStore());
			request.setAttribute("item", item);
			request.setAttribute("type_list", type_list);
		}
		else{
			Integer storeId = Integer.valueOf(request.getParameter("store"));
			Store store = StoreFacade.getStore(storeId);
			List type_list = OrderFacade.getItemTypes(store.getStoreId());
			request.setAttribute("store", store);
			request.setAttribute("type_list", type_list);
		}
		return mapping.findForward("edit");
	}
}