/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.ymai.hibernate.HibernateSessionFactory;
import com.ymai.hibernate.User;
import com.ymai.struts.FormUtil;
import com.ymai.struts.IllegalParameter;
import com.ymai.struts.action.user.UserValidate;
import com.ymai.struts.action.user.u.PasswordForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-02-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PasswordForm p = (PasswordForm) form;
		String old = p.getOld_p();
		String new_p = p.getNew_p();
		String vCode = p.getVcode();
		User current = UserValidate.getUser(request);
		//检查用户登录状态
		if(current == null){
			request.getSession().setAttribute("mess","请先登录。");
			return mapping.findForward("login");
		}
		try {
			FormUtil.checkForm(form);
		} catch (IllegalParameter e) {
			request.setAttribute("mess", "不得输入非法字符,如:<>'等！");
			return mapping.findForward("error");
		}
		if(!vCode.equals(UserValidate.getValidateCodeValue(request))){
			request.setAttribute("mess", "验证码输入错误！");
			return mapping.findForward("error");
		}
		if(!current.getUserPassword().equals(old)){
			request.setAttribute("mess", "旧密码输入错误！");
			return mapping.findForward("error");
		}
		Session session = HibernateSessionFactory.getSession();
		Transaction tran = null;
		try{
			tran = session.beginTransaction();
			tran.begin();
			current = (User) session.load(User.class, current.getUserId());
			current.setUserPassword(new_p);
			UserValidate.setUser(request, current);
			tran.commit();
			session.close();
		}catch(Exception e){
			tran.rollback();
			session.close();
			return mapping.findForward("error");
		}
		return mapping.findForward("ok");
	}
}