/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 05-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="itemImageUpForm"
 */
public class StoreImageUpForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** image property */
	private FormFile image;

	/** itemId property */
	private Integer store;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the image.
	 * @return FormFile
	 */
	public FormFile getImage() {
		return image;
	}

	/** 
	 * Set the image.
	 * @param image The image to set
	 */
	public void setImage(FormFile image) {
		this.image = image;
	}
	
	/** 
	 * Returns the store.
	 * @return Integer
	 */
	public Integer getStore(){return this.store;}
	
	/** 
	 * Set the store.
	 * @param store The store to set
	 */
	public void setStore(Integer store){this.store = store;}
}