/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;
import org.hibernate.Session;

import com.ymai.hibernate.HibernateSessionFactory;
import com.ymai.hibernate.Store;
import com.ymai.hibernate.User;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 05-15-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class StoreImageUpAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		StoreImageUpForm sForm = (StoreImageUpForm) form;
		Integer storeId = sForm.getStore();
		FormFile file = sForm.getImage();
		User current = UserValidate.getUser(request);
		Session session = HibernateSessionFactory.getSessionFactory().getCurrentSession();
		Store store = (Store) session.load(Store.class, storeId);
		response.setContentType("text/html;charset=utf-8"); 
		PrintWriter out = response.getWriter();
		String url  = null;
		if(!UserValidate.canEditStore(request, storeId)){
			out.write("<script type='text/javascript'>parent.callback('权限不足')</script>");
			out.close();
			return null;
		}
		try {
			url = FileUpHelper.saveStoreImage(storeId, file, request);
			out.write("<script type='text/javascript'>parent.callback('上传成功','"+url+"');</script>");
			out.close();
		} catch (Exception e) {
			e.printStackTrace();
			out.write("<script type='text/javascript'>parent.callback('"+e.getMessage()+"')</script>");
			out.close();
		} 
		return null;
	}
}