/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.s;

import java.math.BigInteger;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.User;
import com.ymai.struts.action.user.UserFacade;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 06-01-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserInfoSubmitAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User user = UserValidate.getUser(request);
		if(user == null)
			return mapping.findForward("userLogin");
		String userLName = request.getParameter("userLName");
		String userFName = request.getParameter("userFName");
		String userTele = request.getParameter("userTele");
		if(userTele!=null){
			try{
				Long ut = Long.valueOf(userTele);
				user.setUserTele(BigInteger.valueOf(ut));
			}catch(NumberFormatException e){
				
			}
		}
		user.setUserLName(userLName);
		user.setUserFName(userFName);
		try {
			UserFacade.userInfoEdit(user, request);
			return mapping.findForward("ok");
		} catch (Exception e) {
			request.setAttribute("mess", e.getMessage());
			return mapping.findForward("error");
		}
	}
}