/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.u;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.ymai.struts.FormUtil;
import com.ymai.struts.IllegalParameter;

/** 
 * MyEclipse Struts
 * Creation date: 06-21-2010
 * 
 * XDoclet definition:
 * @struts.form name="evaluateForm"
 */
public class EvaluateForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** speed property */
	private Integer speed;

	/** text property */
	private String text;

	/** favorite property */
	private String favorite;

	/** stars property */
	private Integer stars;

	/** taste property */
	private Integer taste;

	/** health property */
	private Integer health;

	private Integer orderId;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		try {
			FormUtil.checkForm(this);
		} catch (IllegalParameter e) {
			ActionMessages messages = new ActionMessages();
			ActionMessage message = new ActionMessage("illegalParameter");
			messages.add("error", message);
			errors.add(messages);
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the speed.
	 * @return Integer
	 */
	public Integer getSpeed() {
		return speed;
	}

	/** 
	 * Set the speed.
	 * @param speed The speed to set
	 */
	public void setSpeed(Integer speed) {
		this.speed = speed;
	}

	/** 
	 * Returns the text.
	 * @return String
	 */
	public String getText() {
		return text;
	}

	/** 
	 * Set the text.
	 * @param text The text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	/** 
	 * Returns the favorite.
	 * @return String
	 */
	public String getFavorite() {
		return favorite;
	}

	/** 
	 * Set the favorite.
	 * @param favorite The favorite to set
	 */
	public void setFavorite(String favorite) {
		this.favorite = favorite;
	}

	/** 
	 * Returns the stars.
	 * @return Integer
	 */
	public Integer getStars() {
		return stars;
	}

	/** 
	 * Set the stars.
	 * @param stars The stars to set
	 */
	public void setStars(Integer stars) {
		this.stars = stars;
	}

	/** 
	 * Returns the taste.
	 * @return Integer
	 */
	public Integer getTaste() {
		return taste;
	}

	/** 
	 * Set the taste.
	 * @param taste The taste to set
	 */
	public void setTaste(Integer taste) {
		this.taste = taste;
	}

	/** 
	 * Returns the health.
	 * @return Integer
	 */
	public Integer getHealth() {
		return health;
	}

	/** 
	 * Set the health.
	 * @param health The health to set
	 */
	public void setHealth(Integer health) {
		this.health = health;
	}
	
	/** 
	 * Returns the health.
	 * @return Integer
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/** 
	 * Set the health.
	 * @param health The health to set
	 */
	public void setOrderId(Integer id) {
		this.orderId = id;
	}
}