/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.u;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.OrderEvaluate;
import com.ymai.hibernate.User;
import com.ymai.policy.UserJifenPolicy;
import com.ymai.struts.action.user.UserValidate;
import com.ymai.struts.action.user.a.UserAdminFacade;

/** 
 * MyEclipse Struts
 * Creation date: 06-21-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class EvaluateCommitAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		EvaluateForm eform = (EvaluateForm) form;
		OrderEvaluate oe = UserAdminFacade.saveOE(eform, request);
		User user = UserValidate.getUser(request);
		UserJifenPolicy.upDateUser(user, UserJifenPolicy.getPingjiaJifen() , true);
		UserValidate.reFreshUser(request);
		request.setAttribute("order_evaluate", oe);
		return mapping.findForward("show");
	}
}