/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.u;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.Order;
import com.ymai.hibernate.OrderEvaluate;
import com.ymai.struts.action.ActionFacade;
import com.ymai.struts.action.user.a.UserAdminFacade;

/** 
 * MyEclipse Struts
 * Creation date: 06-21-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class EvaluateAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Integer oid = null;
		try{
			oid = Integer.valueOf(request.getParameter("orderId"));
		}catch(Exception e){
			return null;
		}
		Order order = (Order) ActionFacade.get(Order.class, oid);
		OrderEvaluate oe = UserAdminFacade.getOE(oid);
		if(oe == null){
			request.setAttribute("order_id", oid);
			return mapping.findForward("rate");
		}
		else{
			request.setAttribute("order_evaluate", oe);
			return mapping.findForward("show");
		}
	}
	
}