/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.u;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.User;
import com.ymai.struts.action.user.UserFacade;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 06-01-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		LoginForm lf = (LoginForm) form;
		String name = lf.getUsername();
		String pass = lf.getPassword();
		String vcode = lf.getVcode();
		PrintWriter writer = response.getWriter();
		if(!vcode.equals(UserValidate.getValidateCodeValue(request))){
			writer.write(URLEncoder.encode("验证码不正确，请重新输入", "utf-8"));
			writer.close();
			return null;
		}
		User user = UserValidate.login(request,name, pass);
		if(user == null){
			writer.write(URLEncoder.encode("登录失败，请重新登录", "utf-8"));
			writer.close();
			return null;
		}
		if(!user.getUserState().equals(user.STATE_ACTIVE)){
			writer.write(URLEncoder.encode("该账户已暂时失效，请联系管理员", "utf-8"));
			writer.close();
			return null;
		}
		if(user!=null&&user.getUserState().equals(user.STATE_ACTIVE)){
			UserValidate.setUser(request, user);
			writer.write("true");
			writer.close();
			return null;
		}
		return null;
	}
}