/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.u;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.User;
import com.ymai.struts.FormUtil;
import com.ymai.struts.IllegalParameter;
import com.ymai.struts.action.user.UserFacade;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 06-01-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserInfoSubmitAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User user = UserValidate.getUser(request);
		if(user == null)
			return mapping.findForward("userLogin");
		try {
			FormUtil.checkForm(form);
		} catch (IllegalParameter e) {
			request.setAttribute("mess", "不得输入非法字符,如:<>'等！");
			return mapping.findForward("error");
		}
		UserInfoForm f = (UserInfoForm) form;
		String userAddr1 = f.getUserAddr1();
		String userAddr2 = f.getUserAddr2();
		String userAddr3 = f.getUserAddr3();
		user.setUserAddr1(userAddr1);
		user.setUserAddr2(userAddr2);
		user.setUserAddr3(userAddr3);
		try {
			UserFacade.userInfoEdit(user, request);
			return mapping.findForward("ok");
		} catch (Exception e) {
			request.setAttribute("mess", e.getMessage());
			return mapping.findForward("error");
		}
	}
}