/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.u;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.ymai.struts.FormUtil;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2010
 * 
 * XDoclet definition:
 * @struts.form name="userInfoForm"
 */
public class UserInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userAddr2 property */
	private String userAddr2;

	/** userAddr1 property */
	private String userAddr1;

	/** userAddr3 property */
	private String userAddr3;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userAddr2.
	 * @return String
	 */
	public String getUserAddr2() {
		return FormUtil.escape(userAddr2);
	}

	/** 
	 * Set the userAddr2.
	 * @param userAddr2 The userAddr2 to set
	 */
	public void setUserAddr2(String userAddr2) {
		this.userAddr2 = userAddr2;
	}

	/** 
	 * Returns the userAddr1.
	 * @return String
	 */
	public String getUserAddr1() {
		return FormUtil.escape(userAddr1);
	}

	/** 
	 * Set the userAddr1.
	 * @param userAddr1 The userAddr1 to set
	 */
	public void setUserAddr1(String userAddr1) {
		this.userAddr1 = userAddr1;
	}

	/** 
	 * Returns the userAddr3.
	 * @return String
	 */
	public String getUserAddr3() {
		return FormUtil.escape(userAddr3);
	}

	/** 
	 * Set the userAddr3.
	 * @param userAddr3 The userAddr3 to set
	 */
	public void setUserAddr3(String userAddr3) {
		this.userAddr3 = userAddr3;
	}
}