/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.a;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-11-2010
 * 
 * XDoclet definition:
 * @struts.form name="blockEditForm"
 */
public class BlockEditForm  extends ActionForm   {
	/*
	 * Generated fields
	 */

	/** blockName property */
	private String blockName;

	/** area property */
	private Integer area;

	/** city property */
	private Integer city;
	
	/** longitude property */
	private Integer longitude;

	/** latitude property */
	private Integer latitude;

	
	private String uitlName;
	
	private Boolean isBuilding;
	
	/*
	 * Generated Methods
	 */


	/** 
	 * Returns the blockName.
	 * @return String
	 */
	public String getBlockName() {
		return blockName;
	}

	/** 
	 * Set the blockName.
	 * @param blockName The blockName to set
	 */
	public void setBlockName(String blockName) {
		this.blockName = blockName;
	}

	/** 
	 * Returns the area.
	 * @return Integer
	 */
	public Integer getArea() {
		return area;
	}

	/** 
	 * Set the area.
	 * @param area The area to set
	 */
	public void setArea(Integer area) {
		this.area = area;
	}

	/** 
	 * Returns the city.
	 * @return Integer
	 */
	public Integer getCity() {
		return city;
	}

	/** 
	 * Set the city.
	 * @param city The city to set
	 */
	public void setCity(Integer city) {
		this.city = city;
	}
	
	public Integer getLongitude(){
		return this.longitude;
	}
	public Integer getLatitude(){
		return this.latitude;
	}
	
	public void setLongitude(Integer longitude){
		this.longitude = longitude;
	}
	
	public void setLatitude(Integer latitude){
		this.latitude= latitude;
	}
	
	public String getUitlName(){
		return this.uitlName;
	}
	public void setUitlName(String name){
		this.uitlName = name;
	}
	
	public Boolean getIsBuilding(){
		return this.isBuilding;
	}
	public void setIsBuilding(Boolean is){
		this.isBuilding = is;
	}
	
}