/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.a;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.Block;
import com.ymai.struts.FormUtil;

/** 
 * MyEclipse Struts
 * Creation date: 06-11-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BlockEditSubmitAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BlockEditForm bform = (BlockEditForm) form;
		String action = request.getParameter("action");
		
		//防止表单二次提交
		if(!FormUtil.isFromAble(request, "BE_uitlValue", bform.getUitlName()))
			return null;
		FormUtil.disableFrom(request, "BE_uitlValue");
		if(action == null){
			try{	
				AdminFacade.insert(bform);
				request.setAttribute("SUBMIT_URL", "");
				return mapping.findForward("ok");
			}catch(Exception e){
				e.printStackTrace();
				request.setAttribute("BlockEditSubmit_Mess", e.getMessage());
				return mapping.findForward("error");
			}
		}
		if(action.equals("edit")){
			try{	
				Integer blockId = Integer.valueOf(request.getParameter("blockId"));
				AdminFacade.update(bform, blockId);
				request.setAttribute("SUBMIT_URL", "welcome.do?action=blockEdit");
				return mapping.findForward("ok");
			}catch(Exception e){
				e.printStackTrace();
				request.setAttribute("BlockEditSubmit_Mess", e.getMessage());
				return mapping.findForward("error");
			}
		}
		return null;
	}
}