/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.user.a;

import java.math.BigInteger;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-09-2010
 * 
 * XDoclet definition:
 * @struts.form name="storeEditSbumitForm"
 */
public class StoreEditSbumitForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** blockId property */
	private Integer blockId;

	/** storeAddrName property */
	private String storeAddrName;

	/** userId property */
	private Integer userId;

	/** storeId property */
	private Integer storeId;

	/** storeName property */
	private String storeName;

	/** ntuLongitude property */
	private Integer ntuLongitude;

	/** ntulatitude property */
	private Integer ntulatitude;

	/** storeMobile property */
	private BigInteger storeMobile;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the blockId.
	 * @return Integer
	 */
	public Integer getBlockId() {
		return blockId;
	}

	/** 
	 * Set the blockId.
	 * @param blockId The blockId to set
	 */
	public void setBlockId(Integer blockId) {
		this.blockId = blockId;
	}

	/** 
	 * Returns the storeAddrName.
	 * @return String
	 */
	public String getStoreAddrName() {
		return storeAddrName;
	}

	/** 
	 * Set the storeAddrName.
	 * @param storeAddrName The storeAddrName to set
	 */
	public void setStoreAddrName(String storeAddrName) {
		this.storeAddrName = storeAddrName;
	}

	/** 
	 * Returns the userId.
	 * @return Integer
	 */
	public Integer getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the storeId.
	 * @return Integer
	 */
	public Integer getStoreId() {
		return storeId;
	}

	/** 
	 * Set the storeId.
	 * @param storeId The storeId to set
	 */
	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	/** 
	 * Returns the storeName.
	 * @return String
	 */
	public String getStoreName() {
		return storeName;
	}

	/** 
	 * Set the storeName.
	 * @param storeName The storeName to set
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	/** 
	 * Returns the ntuLongitude.
	 * @return Integer
	 */
	public Integer getNtuLongitude() {
		return ntuLongitude;
	}

	/** 
	 * Set the ntuLongitude.
	 * @param ntuLongitude The ntuLongitude to set
	 */
	public void setNtuLongitude(Integer ntuLongitude) {
		this.ntuLongitude = ntuLongitude;
	}

	/** 
	 * Returns the ntulatitude.
	 * @return Integer
	 */
	public Integer getNtulatitude() {
		return ntulatitude;
	}

	/** 
	 * Set the ntulatitude.
	 * @param ntulatitude The ntulatitude to set
	 */
	public void setNtulatitude(Integer ntulatitude) {
		this.ntulatitude = ntulatitude;
	}

	/** 
	 * Returns the storeMobile.
	 * @return Integer
	 */
	public BigInteger getStoreMobile() {
		return storeMobile;
	}

	/** 
	 * Set the storeMobile.
	 * @param storeMobile The storeMobile to set
	 */
	public void setStoreMobile(BigInteger storeMobile) {
		this.storeMobile = storeMobile;
	}
}