/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.order;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.User;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AddComntAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		try {
			response.setCharacterEncoding("utf-8");
			AddComntForm af = (AddComntForm) form;
			OrderFacade.addComnt(form, request);
			response.getWriter().write("true");
			return null;
		} catch (Exception e) {
			response.getWriter().write(e.getMessage());
			e.printStackTrace();
		}
		return null;
	}
}