/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.order;

import java.math.BigInteger;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.ymai.struts.FormUtil;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2010
 * 
 * XDoclet definition:
 * @struts.form name="addOrderForm"
 */
public class AddOrderForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** tele property */
	private BigInteger tele;
	
	private String mrMiss;

	/** others property */
	private String others;

	/** storeId property */
	private Integer storeId;

	/** address property */
	private String address;

	/** itemIds property */
	private Integer[] itemIds;

	/** name property */
	private String name;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the tele.
	 * @return BigInteger
	 */
	public BigInteger getTele() {
		return tele;
	}

	/** 
	 * Set the tele.
	 * @param tele The tele to set
	 */
	public void setTele(BigInteger tele) {
		this.tele = tele;
	}

	/** 
	 * Returns the others.
	 * @return String
	 */
	public String getOthers() {
		return FormUtil.escape(others);
	}

	/** 
	 * Set the others.
	 * @param others The others to set
	 */
	public void setOthers(String others) {
		this.others = others;
	}

	/** 
	 * Returns the storeId.
	 * @return Integer
	 */
	public Integer getStoreId() {
		return storeId;
	}

	/** 
	 * Set the storeId.
	 * @param storeId The storeId to set
	 */
	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return FormUtil.escape(address);
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the itemIds.
	 * @return Integer[]
	 */
	public Integer[] getItemIds() {
		return itemIds;
	}

	/** 
	 * Set the itemIds.
	 * @param itemIds The itemIds to set
	 */
	public void setItemIds(Integer[] itemIds) {
		this.itemIds = itemIds;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return FormUtil.escape(name+this.mrMiss);
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	public String getMrMiss(){
		return FormUtil.escape(this.mrMiss);
	}
	
	public void setMrMiss(String mrms){
		this.mrMiss = mrms;
	}
}