/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.order;

import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.criterion.Example;

import com.ymai.hibernate.Area;
import com.ymai.hibernate.Block;
import com.ymai.hibernate.HibernateSessionFactory;
import com.ymai.struts.action.MapFacade;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BlockListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Integer areaId = Integer.valueOf(request.getParameter("area"));
		String firstLetter = request.getParameter("fl");
		if(firstLetter == null) firstLetter = "A";
		Area area = OrderFacade.getArea(areaId);
		List list_s = OrderFacade.getBlocksNotEmpty(areaId, firstLetter,Block.BLOCK_TYPE_STREE);
		List list_b = OrderFacade.getBlocksNotEmpty(areaId, firstLetter,Block.BLOCK_TYPE_BUSSTOP);

		Set<Area> all_area = MapFacade.currentCity(request).getAreas();
		request.setAttribute("area", area);
		request.setAttribute("block_list_street", list_s);
		request.setAttribute("block_list_bus", list_b);
		request.setAttribute("first_letter", firstLetter);
		return mapping.findForward("list");
	}
}