/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.order;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.Store;
import com.ymai.struts.Page;
import com.ymai.struts.action.ActionFacade;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetCommentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String iframe = request.getParameter("iframe");
		String type= request.getParameter("type");
		String curStr = request.getParameter("page");
		String eachPageStr =  request.getParameter("eachPage");
		Integer storeId = Integer.valueOf(request.getParameter("store"));
		Integer cur = 0;
		Integer eachPage = 5;
		if(curStr!=null)cur = Integer.valueOf(curStr);
		if(eachPageStr!=null)cur = Integer.valueOf(eachPageStr);
		Store store = (Store) ActionFacade.load(Store.class,storeId);
		request.setAttribute("store",store);
		if(type == null ){
			if(iframe == null) iframe = "comment";
			request.setAttribute("type", iframe);
			return mapping.findForward("main");
		}
		if(type.equals("all")){
			Page page = OrderFacade.getAllComntPage(storeId, cur, eachPage);
			request.setAttribute("page", page);
			return mapping.findForward("all");
		}
		if(type.equals("comment")){
			Page page = OrderFacade.getOEPage(storeId, cur, eachPage);
			request.setAttribute("page", page);
			return mapping.findForward("comment");
		}
		if(type.equals("liuyan")){
			Page page = OrderFacade.getSCPage(storeId, cur, eachPage);
			request.setAttribute("page", page);
			return mapping.findForward("liuyan");
		}
		return null;
	}
}