/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.order;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ymai.hibernate.Order;
import com.ymai.struts.CookieUtil;
import com.ymai.struts.FormUtil;
import com.ymai.struts.action.user.UserFacade;
import com.ymai.struts.action.user.UserValidate;

/** 
 * MyEclipse Struts
 * Creation date: 07-07-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OrderCommitValidateAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		String vcode = FormUtil.escape(request.getParameter("J_Code"));
		String orign = UserFacade.getAcitveCode(request);
		if(!vcode.equals(orign)){
			response.getWriter().write("-1");
			response.getWriter().close();
			return null;
		}
		try{
			Order order = UserValidate.getOrder(request);
			OrderLife.setOrderToAudit(request);
			UserFacade.clearAcitveCode(request);
			CookieUtil.setPhoneCodeinCookie(order.getOrderTele(), request, response);
			response.getWriter().write("1");
			response.getWriter().close();
			return null;
		}catch(Exception e){
			e.printStackTrace();
			response.getWriter().write("-2");
			response.getWriter().close();
			return null;
		}
	}
}