/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action.order;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Hibernate;
import org.hibernate.Session;

import com.ymai.hibernate.Block;
import com.ymai.hibernate.HibernateSessionFactory;
import com.ymai.hibernate.Store;
import com.ymai.struts.CookieUtil;
import com.ymai.struts.action.ActionFacade;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class StoreAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Integer storeId = Integer.valueOf(request.getParameter("store"));
		String bid = request.getParameter("block");
		if(bid!=null){
			Block block = (Block) ActionFacade.get(Block.class, Integer.valueOf(bid));
			request.setAttribute("u_block", block);
		}
		Store store = OrderFacade.getStoreAndItsItems(storeId);
		List type_list = OrderFacade.getItemTypes(storeId);
		String address = CookieUtil.getAddressInCookies(request);
		request.setAttribute("used_address",address);
		request.setAttribute("store", store);
		request.setAttribute("type_list", type_list);
		return mapping.findForward("store");
	}
}