/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ymai.struts.action;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.ymai.struts.FormUtil;

/** 
 * MyEclipse Struts
 * Creation date: 07-06-2010
 * 
 * XDoclet definition:
 * @struts.form name="adviseForm"
 */
public class AdviseForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** adviseContent property */
	private String adviseContent;

	/** adviseName property */
	private String adviseName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the adviseContent.
	 * @return String
	 */
	public String getAdviseContent() {
		return FormUtil.escape(adviseContent);
	}

	/** 
	 * Set the adviseContent.
	 * @param adviseContent The adviseContent to set
	 */
	public void setAdviseContent(String adviseContent) {
		this.adviseContent = adviseContent;
	}

	/** 
	 * Returns the adviseName.
	 * @return String
	 */
	public String getAdviseName() {
		return FormUtil.escape(adviseName);
	}

	/** 
	 * Set the adviseName.
	 * @param adviseName The adviseName to set
	 */
	public void setAdviseName(String adviseName) {
		this.adviseName = adviseName;
	}
}